# M RAVI ACHYAR TRISTA ZHAID
# 1124102193

a = int(input('Masukkan Angka a:'))
b = int(input('Masukkan Angka b:'))
c = int(input('Masukkan Angka c:'))
d = int(input('Masukkan Angka d:'))

print('OPERATOR AND')
print((a>b) and (c>d))
print((a<b) and (c>d))
print((a<b) and (c<d))
print((a>b) and (c<d))
print()
print((a==b) and (c==d))
print((a==b) and (c==d))
print((a==b) and (c==d))
print((a==b) and (c==d))
print()
print('OPERATOR OR')
print((a>b) or (c>d))
print((a<b) or (c>d))
print((a<b) or (c<d))
print((a>b) or (c<d))
print()
print((a!=b) or (c==d))
print((a!=b) or (c==d))
print((a!=b) or (c==d))
print((a!=b) or (c==d))
print()
print('OPERATOR NOT')
print(not(a>b))
print(not(a<b))
print(not(a<b))
print(not(a>b)) 